# Generated by Django 5.2.18 on 2026-10-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('meeting', 'Встреча')], default='call', max_length=20)),
                ('happened_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='clients.client')),
            ],
            options={
                'ordering': ['-happened_at'],
            },
        ),
    ]
