# Generated by Django 5.2.18 on 2026-10-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_interaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-happened_at'], 'verbose_name': 'Взаимодействие', 'verbose_name_plural': 'Взаимодействия'},
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('lead', 'Лид'), ('active', 'Активный'), ('inactive', 'Неактивный')], default='lead', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='happened_at',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('meeting', 'Встреча')], default='call', max_length=20, verbose_name='Тип'),
        ),
    ]
